{
 "title": "Spring Boot 3 Throughput",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application", "query": { "query": "label_values(application)" } }
  ]
 },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server Request Avg Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(uri)(http_server_requests_seconds_sum{application=\"$application\"}) / sum by(uri)(http_server_requests_seconds_count{application=\"$application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Request Avg Duration",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri)(http_server_requests_seconds_sum{application=\"$application\"}) / sum by(uri)(http_server_requests_seconds_count{application=\"$application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Request Per Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(uri)(rate(http_server_requests_seconds_count{application=\"$application\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Client Request Avg Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(uri)(http_client_requests_seconds_sum{application=\"$application\"}) / sum by(uri)(http_client_requests_seconds_count{application=\"$application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client Request Avg Duration",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(uri)(http_client_requests_seconds_sum{application=\"$application\"}) / sum by(uri)(http_client_requests_seconds_count{application=\"$application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Database (Jooq)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Database SQL Avg Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(name)(jooq_query_seconds_sum{application=\"$application\"}) / sum by(name)(jooq_query_seconds_count{application=\"$application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database SQL Avg Duration",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(name)(jooq_query_seconds_sum{application=\"$application\"}) / sum by(name)(jooq_query_seconds_count{application=\"$application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database DAO method Avg Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(method)(orderDao_seconds_sum{application=\"$application\"}) / sum by(method)(orderDao_seconds_count{application=\"$application\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database DAO Method Avg Duration",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(method)(orderDao_seconds_sum{application=\"$application\"}) / sum by(method)(orderDao_seconds_count{application=\"$application\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}