apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: java-spring-monitoring
build:
  local:
    concurrency: 3
  artifacts:
    - image: bitxon/price-app
      context: price-service
      docker:
        dockerfile: Dockerfile
    - image: bitxon/order-app
      context: order-service
      docker:
        dockerfile: Dockerfile
    - image: bitxon/sba-app
      context: spring-boot-admin
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/monitoring/namespace.yaml
    - k8s/monitoring/prometheus-rbac.yaml
    - k8s/monitoring/prometheus-deployment.yaml
    - k8s/monitoring/grafana-deployment.yaml
    - k8s/monitoring/zipkin.yaml
    - k8s/db.yaml
    - k8s/sba-rbac.yaml
    - k8s/sba-application.yaml
    - k8s/price-application.yaml
    - k8s/order-application.yaml
portForward:
  - resourceName: price-service
    resourceType: service
    namespace: default
    port: 8080
    localPort: 8090
  - resourceName: order-service
    resourceType: service
    namespace: default
    port: 8080
    localPort: 8080
  - resourceName: zipkin-service
    resourceType: service
    namespace: monitoring
    port: 9411
    localPort: 9411
  - resourceName: sba-service
    resourceType: service
    namespace: default
    port: 8080
    localPort: 9999
  - resourceName: prometheus-service
    resourceType: service
    namespace: monitoring
    port: 9090
    localPort: 9090
  - resourceName: grafana-service
    resourceType: service
    namespace: monitoring
    port: 3000
    localPort: 3000
