apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: java-spring-monitoring
build:
  local:
    concurrency: 3
  artifacts:
    - image: bitxon/price-app
      context: price-service
      docker:
        dockerfile: Dockerfile
    - image: bitxon/order-app
      context: order-service
      docker:
        dockerfile: Dockerfile
    - image: bitxon/sba-app
      context: spring-boot-admin
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/account.yaml
    - k8s/zipkin.yaml
    - k8s/sba.yaml
    - k8s/db.yaml
    - k8s/price-application.yaml
    - k8s/order-application.yaml
portForward:
  - resourceName: price-service
    resourceType: service
    port: 8080
    localPort: 8090
  - resourceName: order-service
    resourceType: service
    port: 8080
    localPort: 8080
  - resourceName: zipkin-service
    resourceType: service
    port: 9411
    localPort: 9411
  - resourceName: sba-service
    resourceType: service
    port: 8080
    localPort: 9999