apiVersion: 1

datasources:
  - name: Prometheus
    uid: Prometheus # Make sure you use uid in dashboard *.json files
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.47.0
      cacheLevel: 'High'