spring:
  profiles:
    default: local
  application:
    name: sba-service
  cloud:
    kubernetes:
      discovery:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always